run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - gofmt
    - goimports
    - gosec
    - gocritic
    - gocyclo
    - dupl
    - unconvert
    - prealloc
    - exportloopref
    - goconst
    - unparam
    - nakedret
    - lll
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  unparam:
    check-exported: false

  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
